name: Info KRL
description: 'Real-time Commuterline train schedules'
full_description: 'Info KRL is a mobile app that provides information about KRL Commuterline services in Indonesia.<br>
<br>Features include:
<br>- Real-time Train Schedules
<br>- Live Location of Trains
<br>- Transit Information
<br>- Fare Calculator'
android: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
